### ISSUE TITLE
cant find package on packagist

### ISSUE THREAD

**Issue by schandrasekhar** [Woopra/woopra-php-sdk#2]
Hi 
This is not working 
composer require woopra/woopra-php-sdk
It looks like its changed to 
composer require woopra/woopra   ( https://packagist.org/packages/woopra/woopra )

Just a heads up.
Thanks

**Comment by alexandrtutkevich** [comment]
Try to call command:
composer require woopra/woopra:dev-master

**Comment by ultrasamad** [comment]
I think the readme should be updated to indicate the right package version to install

**Comment by tyscorp** [comment]
I updated the readme
