### ISSUE TITLE
Bug with app variable

### ISSUE THREAD

**Issue by lludwig** [Woopra/woopra-php-sdk#5]
When defining the app in a new object.

ie new WoopraTracker(array('app' => 'clickmeter', ...

it uses 'ce_app=' as the variable to pass to Woopra. This isn't correct, it should be' app='.

**Comment by lludwig** [comment]
The 'app' option is also missing from your API documentation on your website.

**Comment by tyscorp** [comment]
Thanks! It has been fixed.
